// Static, human-quality translations of the article page's repeating UI
// chrome (nav, breadcrumb, footer, consent banner, author box). Curated
// once per language rather than run through the free MT package on every
// publish — this boilerplate never changes per-article, and machine
// translation of fixed corporate/legal copy (the author box, footer
// operator line) reads worse and less predictably than a one-time human
// translation reused every run. Only per-article body content (headline,
// paragraphs, table cells, blockquote) goes through scripts/lib/translate.js.
//
// If you add a language here, also add it to LANG_ORDER in lang-meta.js
// and gen_i18n.py.

const CHROME_STRINGS = {
  en: {
    tagline: 'Zero logins • 2-second summary',
    backToApp: 'Back to app',
    breadcrumbHome: 'Home',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'min read',
    reviewedBy: 'Reviewed by the SyllabusTLDR academic advising team',
    aboutAuthorHeading: 'About the Author',
    authorBoxHtml: 'Written by the Academic Engineering Team at <strong>EIGHTFINITY LTD</strong>. We build open-access, browser-side tools designed to reduce cognitive load and combat academic overwhelm for higher education students worldwide. Registered in the United Kingdom. Need support? Reach us directly at info@eightfinity.net.',
    footerApp: 'App',
    footerAbout: 'About',
    footerContact: 'Contact',
    footerBlog: 'Blog',
    footerTerms: 'Terms of Service',
    footerPrivacy: 'Privacy Policy',
    copyrightLine: '© 2026 SyllabusTLDR • Built for fast mobile execution.',
    operatorLine: 'SyllabusTLDR is operated by EIGHTFINITY LTD, a registered company in the United Kingdom.',
    consentText: 'We use cookies for analytics and, once ads are enabled, to show relevant ads. Read our',
    consentReject: 'Reject',
    consentAccept: 'Accept All',
  },
  es: {
    tagline: 'Sin inicio de sesión • Resumen en 2 segundos',
    backToApp: 'Volver a la app',
    breadcrumbHome: 'Inicio',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'min de lectura',
    reviewedBy: 'Revisado por el equipo de asesoría académica de SyllabusTLDR',
    aboutAuthorHeading: 'Sobre el autor',
    authorBoxHtml: 'Escrito por el Equipo de Ingeniería Académica de <strong>EIGHTFINITY LTD</strong>. Creamos herramientas de acceso abierto que funcionan en el navegador, diseñadas para reducir la carga cognitiva y combatir el agotamiento académico de estudiantes universitarios en todo el mundo. Registrada en el Reino Unido. ¿Necesitas ayuda? Escríbenos directamente a info@eightfinity.net.',
    footerApp: 'App',
    footerAbout: 'Acerca de',
    footerContact: 'Contacto',
    footerBlog: 'Blog',
    footerTerms: 'Términos del servicio',
    footerPrivacy: 'Política de privacidad',
    copyrightLine: '© 2026 SyllabusTLDR • Diseñado para uso móvil rápido.',
    operatorLine: 'SyllabusTLDR está operado por EIGHTFINITY LTD, una empresa registrada en el Reino Unido.',
    consentText: 'Usamos cookies para análisis y, una vez que se activen los anuncios, para mostrar anuncios relevantes. Lee nuestra',
    consentReject: 'Rechazar',
    consentAccept: 'Aceptar todo',
  },
  fr: {
    tagline: "Sans connexion • Résumé en 2 secondes",
    backToApp: "Retour à l'appli",
    breadcrumbHome: 'Accueil',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'min de lecture',
    reviewedBy: "Relu par l'équipe de conseil académique de SyllabusTLDR",
    aboutAuthorHeading: "À propos de l'auteur",
    authorBoxHtml: "Rédigé par l'équipe d'ingénierie académique d'<strong>EIGHTFINITY LTD</strong>. Nous concevons des outils en accès libre, exécutés entièrement dans le navigateur, pour réduire la charge cognitive et lutter contre la surcharge académique des étudiants du monde entier. Société immatriculée au Royaume-Uni. Besoin d'aide ? Contactez-nous directement à info@eightfinity.net.",
    footerApp: 'Appli',
    footerAbout: 'À propos',
    footerContact: 'Contact',
    footerBlog: 'Blog',
    footerTerms: "Conditions d'utilisation",
    footerPrivacy: 'Politique de confidentialité',
    copyrightLine: '© 2026 SyllabusTLDR • Conçu pour une utilisation mobile rapide.',
    operatorLine: 'SyllabusTLDR est exploité par EIGHTFINITY LTD, société immatriculée au Royaume-Uni.',
    consentText: 'Nous utilisons des cookies à des fins d’analyse et, une fois les publicités activées, pour afficher des annonces pertinentes. Consultez notre',
    consentReject: 'Refuser',
    consentAccept: 'Tout accepter',
  },
  pt: {
    tagline: 'Sem login • Resumo em 2 segundos',
    backToApp: 'Voltar ao app',
    breadcrumbHome: 'Início',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'min de leitura',
    reviewedBy: 'Revisado pela equipe de orientação acadêmica do SyllabusTLDR',
    aboutAuthorHeading: 'Sobre o autor',
    authorBoxHtml: 'Escrito pela Equipe de Engenharia Acadêmica da <strong>EIGHTFINITY LTD</strong>. Criamos ferramentas de acesso aberto, que rodam no navegador, feitas para reduzir a carga cognitiva e combater a sobrecarga acadêmica de estudantes universitários no mundo todo. Registrada no Reino Unido. Precisa de ajuda? Fale conosco em info@eightfinity.net.',
    footerApp: 'App',
    footerAbout: 'Sobre',
    footerContact: 'Contato',
    footerBlog: 'Blog',
    footerTerms: 'Termos de Serviço',
    footerPrivacy: 'Política de Privacidade',
    copyrightLine: '© 2026 SyllabusTLDR • Feito para uso rápido no celular.',
    operatorLine: 'O SyllabusTLDR é operado pela EIGHTFINITY LTD, empresa registrada no Reino Unido.',
    consentText: 'Usamos cookies para análises e, quando os anúncios forem ativados, para exibir anúncios relevantes. Leia nossa',
    consentReject: 'Rejeitar',
    consentAccept: 'Aceitar tudo',
  },
  zh: {
    tagline: '无需登录 • 2 秒摘要',
    backToApp: '返回应用',
    breadcrumbHome: '首页',
    breadcrumbBlog: '博客',
    readTimeSuffix: '分钟阅读',
    reviewedBy: '由 SyllabusTLDR 学术顾问团队审核',
    aboutAuthorHeading: '关于作者',
    authorBoxHtml: '由 <strong>EIGHTFINITY LTD</strong> 学术工程团队撰写。我们打造完全在浏览器端运行、开放获取的工具，旨在为全球高等院校学生减轻认知负担、缓解学业压力。公司注册于英国。需要帮助？请直接联系 info@eightfinity.net。',
    footerApp: '应用',
    footerAbout: '关于我们',
    footerContact: '联系我们',
    footerBlog: '博客',
    footerTerms: '服务条款',
    footerPrivacy: '隐私政策',
    copyrightLine: '© 2026 SyllabusTLDR • 专为快速移动端使用而设计。',
    operatorLine: 'SyllabusTLDR 由 EIGHTFINITY LTD 运营，该公司在英国注册。',
    consentText: '我们使用 Cookie 进行数据分析，广告功能启用后还将用于展示相关广告。请阅读我们的',
    consentReject: '拒绝',
    consentAccept: '全部接受',
  },
  de: {
    tagline: 'Kein Login • Zusammenfassung in 2 Sekunden',
    backToApp: 'Zurück zur App',
    breadcrumbHome: 'Start',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'Min. Lesezeit',
    reviewedBy: 'Geprüft vom akademischen Beratungsteam von SyllabusTLDR',
    aboutAuthorHeading: 'Über den Autor',
    authorBoxHtml: 'Verfasst vom Academic Engineering Team von <strong>EIGHTFINITY LTD</strong>. Wir entwickeln frei zugängliche, browserbasierte Tools, die die kognitive Belastung senken und akademischer Überforderung von Studierenden weltweit entgegenwirken. Eingetragen im Vereinigten Königreich. Fragen? Schreiben Sie uns direkt an info@eightfinity.net.',
    footerApp: 'App',
    footerAbout: 'Über uns',
    footerContact: 'Kontakt',
    footerBlog: 'Blog',
    footerTerms: 'Nutzungsbedingungen',
    footerPrivacy: 'Datenschutzerklärung',
    copyrightLine: '© 2026 SyllabusTLDR • Für schnelle mobile Nutzung entwickelt.',
    operatorLine: 'SyllabusTLDR wird von EIGHTFINITY LTD betrieben, einem im Vereinigten Königreich eingetragenen Unternehmen.',
    consentText: 'Wir verwenden Cookies für Analysen und, sobald Anzeigen aktiviert sind, um relevante Werbung zu zeigen. Lesen Sie unsere',
    consentReject: 'Ablehnen',
    consentAccept: 'Alle akzeptieren',
  },
  hi: {
    tagline: 'बिना लॉगिन • 2 सेकंड में सारांश',
    backToApp: 'ऐप पर वापस जाएं',
    breadcrumbHome: 'होम',
    breadcrumbBlog: 'ब्लॉग',
    readTimeSuffix: 'मिनट का पठन',
    reviewedBy: 'SyllabusTLDR की शैक्षणिक सलाहकार टीम द्वारा समीक्षित',
    aboutAuthorHeading: 'लेखक के बारे में',
    authorBoxHtml: '<strong>EIGHTFINITY LTD</strong> की Academic Engineering Team द्वारा लिखित। हम पूरी तरह ब्राउज़र में चलने वाले, खुले-उपयोग वाले टूल बनाते हैं, जो दुनिया भर के उच्च शिक्षा छात्रों के मानसिक बोझ को कम करने और अकादमिक तनाव से निपटने के लिए डिज़ाइन किए गए हैं। यूनाइटेड किंगडम में पंजीकृत। सहायता चाहिए? सीधे info@eightfinity.net पर संपर्क करें।',
    footerApp: 'ऐप',
    footerAbout: 'हमारे बारे में',
    footerContact: 'संपर्क करें',
    footerBlog: 'ब्लॉग',
    footerTerms: 'सेवा की शर्तें',
    footerPrivacy: 'गोपनीयता नीति',
    copyrightLine: '© 2026 SyllabusTLDR • तेज़ मोबाइल उपयोग के लिए बनाया गया।',
    operatorLine: 'SyllabusTLDR का संचालन EIGHTFINITY LTD करती है, जो यूनाइटेड किंगडम में पंजीकृत एक कंपनी है।',
    consentText: 'हम एनालिटिक्स के लिए और विज्ञापन सक्षम होने के बाद प्रासंगिक विज्ञापन दिखाने के लिए कुकीज़ का उपयोग करते हैं। हमारी नीति पढ़ें',
    consentReject: 'अस्वीकार करें',
    consentAccept: 'सभी स्वीकार करें',
  },
  ar: {
    tagline: 'بدون تسجيل دخول • ملخص خلال ثانيتين',
    backToApp: 'العودة إلى التطبيق',
    breadcrumbHome: 'الرئيسية',
    breadcrumbBlog: 'المدونة',
    readTimeSuffix: 'دقائق قراءة',
    reviewedBy: 'راجعه فريق الاستشارات الأكاديمية في SyllabusTLDR',
    aboutAuthorHeading: 'عن الكاتب',
    authorBoxHtml: 'بقلم فريق الهندسة الأكاديمية في <strong>EIGHTFINITY LTD</strong>. نصمّم أدوات مفتوحة الوصول تعمل بالكامل داخل المتصفح، لتقليل العبء الذهني ومواجهة الإرهاق الأكاديمي لدى طلاب التعليم العالي حول العالم. الشركة مسجّلة في المملكة المتحدة. هل تحتاج إلى مساعدة؟ راسلنا مباشرة على info@eightfinity.net.',
    footerApp: 'التطبيق',
    footerAbout: 'نبذة عنا',
    footerContact: 'تواصل معنا',
    footerBlog: 'المدونة',
    footerTerms: 'شروط الخدمة',
    footerPrivacy: 'سياسة الخصوصية',
    copyrightLine: '© 2026 SyllabusTLDR • مصمم للاستخدام السريع على الجوال.',
    operatorLine: 'يتم تشغيل SyllabusTLDR بواسطة EIGHTFINITY LTD، وهي شركة مسجّلة في المملكة المتحدة.',
    consentText: 'نستخدم ملفات تعريف الارتباط لأغراض التحليل، وبعد تفعيل الإعلانات، لعرض إعلانات ذات صلة. اقرأ',
    consentReject: 'رفض',
    consentAccept: 'قبول الكل',
  },
  ko: {
    tagline: '로그인 필요 없음 • 2초 요약',
    backToApp: '앱으로 돌아가기',
    breadcrumbHome: '홈',
    breadcrumbBlog: '블로그',
    readTimeSuffix: '분 소요',
    reviewedBy: 'SyllabusTLDR 학업 상담팀 검토',
    aboutAuthorHeading: '작성자 소개',
    authorBoxHtml: '<strong>EIGHTFINITY LTD</strong>의 Academic Engineering Team이 작성했습니다. 저희는 전 세계 대학생들의 인지 부담을 줄이고 학업 번아웃에 대응하기 위해 브라우저에서 전적으로 작동하는 무료 개방형 도구를 만듭니다. 영국에 등록된 회사입니다. 도움이 필요하신가요? info@eightfinity.net으로 직접 문의해 주세요.',
    footerApp: '앱',
    footerAbout: '소개',
    footerContact: '문의하기',
    footerBlog: '블로그',
    footerTerms: '이용약관',
    footerPrivacy: '개인정보 처리방침',
    copyrightLine: '© 2026 SyllabusTLDR • 빠른 모바일 사용을 위해 제작되었습니다.',
    operatorLine: 'SyllabusTLDR는 영국에 등록된 회사인 EIGHTFINITY LTD가 운영합니다.',
    consentText: '저희는 분석을 위해, 그리고 광고가 활성화되면 관련 광고를 표시하기 위해 쿠키를 사용합니다. 자세한 내용은 아래를 참고해 주세요:',
    consentReject: '거부',
    consentAccept: '모두 수락',
  },
  vi: {
    tagline: 'Không cần đăng nhập • Tóm tắt trong 2 giây',
    backToApp: 'Quay lại ứng dụng',
    breadcrumbHome: 'Trang chủ',
    breadcrumbBlog: 'Blog',
    readTimeSuffix: 'phút đọc',
    reviewedBy: 'Được đội ngũ cố vấn học thuật của SyllabusTLDR xem xét',
    aboutAuthorHeading: 'Về tác giả',
    authorBoxHtml: 'Được viết bởi Academic Engineering Team tại <strong>EIGHTFINITY LTD</strong>. Chúng tôi xây dựng các công cụ truy cập mở, chạy hoàn toàn trên trình duyệt, nhằm giảm tải nhận thức và chống lại tình trạng quá tải học tập cho sinh viên đại học trên toàn thế giới. Đăng ký kinh doanh tại Vương quốc Anh. Cần hỗ trợ? Liên hệ trực tiếp với chúng tôi qua info@eightfinity.net.',
    footerApp: 'Ứng dụng',
    footerAbout: 'Giới thiệu',
    footerContact: 'Liên hệ',
    footerBlog: 'Blog',
    footerTerms: 'Điều khoản dịch vụ',
    footerPrivacy: 'Chính sách quyền riêng tư',
    copyrightLine: '© 2026 SyllabusTLDR • Được xây dựng để sử dụng nhanh trên di động.',
    operatorLine: 'SyllabusTLDR được vận hành bởi EIGHTFINITY LTD, một công ty đã đăng ký tại Vương quốc Anh.',
    consentText: 'Chúng tôi sử dụng cookie để phân tích và, khi quảng cáo được bật, để hiển thị quảng cáo phù hợp. Đọc',
    consentReject: 'Từ chối',
    consentAccept: 'Chấp nhận tất cả',
  },
};

export { CHROME_STRINGS };
